audit_header: false
title: "Middle Tennessee's Best Real Estate Training"
description: Monte Mohr, a top Real Estate Agent in Middle Tennessee, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
  - title: Free Trainings
    url: /training/
  - title: About Us
    url: /about/
  - title: Radio Show
    url: http://www.talkmusiccity.podbean.com/?fbclid=IwAR0AtR-USmTy31k_9B0O6t0N8Wmp_9K5pp3Qkk9OlmDiZeQj9tsNCmL1fIA
client:
  name: Monte Mohr
  title:
  license_number:
  about_markdown: |
    Monte has been in real estate for over 35 years. Throughout his career he has owned 4 real estate companies and has personally sold over 3,000 homes, not counting team production. He’s written a book titled Your Middle Tennessee Home Seller’s Guide, Secrets to Getting Top Dollar in Today’s Market and was a writer for the Tennessean for 2 years, where he published over 100 articles. He has been on NBC’s Chan 4 over 100 times answering local homeowners questions, and is currently the co-host of the weekly radio show on WTN’s SuperTalk 99-7 called “The Talk of Music City Real Estate.” Go give it a listen - you can find the podcast under that name on Facebook, Stitcher, iTunes, etc.!

    Monte has stepped away from being a top producing sales person since opening Realty ONE Group Music City to focus on becoming the guide for each of his agents and assisting them in growing their individual businesses.

    “This is my legacy. As their guide, our agents don’t have to go through what I did over the past 3 ½ decades. My heart's desire is to equip each one to become their very best and to reach levels of success they had only dreamed of.”  - Monte Mohr

  market: Middle Tennessee
  brand: Realty ONE Group Music City
  brokerage:
  address: 600A Frazier Drive Suite 123 Franklin Tn. 37067<br>(Next to Cool Springs Brewery and Sperry's Restaurant)
  phone: 615-636-8244
  phone_type:
  phone2:
  phone2_type:
  email: monte@realtyonemusiccity.com
  url: http://TopAgentSuccessCoach.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Realty ONE Group Music City can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/mohr-nashville-realestatebroker/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Middle Tennessee Real Estate Podcast with Monte Mohr'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Middle Tennessee Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Realty ONE Group Music City - your professional Middle Tennessee Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Middle Tennessee, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Monte Mohr'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Middle Tennessee Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c7aa5f'
  theme_color: '#404041'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#c7aa5f'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
